### Obtener todos los usuarios
GET http://localhost:8080/api/usuarios?pagina=0

### Obtener todos los usuarios de Armenia
GET http://localhost:8080/api/usuarios?pagina=0&ciudad=armenia

### Obtener un usuario por su id
GET http://localhost:8080/api/usuarios/1

### Crear un usuario
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
  "nombre": "Carlos",
  "ciudad": "ARMENIA",
  "direccion": "Calle 123",
  "telefono": "121212",
  "email": "carlos@email.com",
  "password": "12345678"
}

### Actualizar un usuario
PUT http://localhost:8080/api/usuarios
Content-Type: application/json

{
  "id": "aaa",
  "nombre": "Carlos",
  "ciudad": "ARMENIA",
  "direccion": "Calle 123",
  "email": "carlos@email.com",
  "password": "123456"
}

### Eliminar un usuario
DELETE http://localhost:8080/api/usuarios/1
